# docker network create mysql_network
# docker volume create mysql_data

version: "3.7" 
services:
  mysql: 
    image: mysql
    restart: always
    command: 
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: 7455
      TZ: Asia/Seoul
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql_network

networks:
  mysql_network:
    external: true

volumes:
  mysql_data:
    external: true