# docker network create mongo_network
# docker volume create mongo_data

version: "3.7" 
services:
  mongo: 
    image: mongo
    restart: always
    command: [--auth]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 7455
    volumes:
      - mongo_data:/var/lib/mysql
    networks:
      - mongo_network

  express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 7455
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 7455
    networks:
      - mongo_network

networks:
  mongo_network:
    external: true

volumes:
  mongo_data:
    external: true